version: "3"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: qwerty@123
    volumes:
      - sqlserver-data:/var/opt/mssql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  sqlserver-data:
